WITH snap AS (
    SELECT SNAPSHOT_DATE, CSP_ID, UPPER(TRIM(T2_BAND)) AS STATE
    FROM PROD_DB.CSP_QUALITY_SERVICE_CSP_QUALITY_SERVICE.DAILY_METRIC_SNAPSHOTS
    WHERE _FIVETRAN_ACTIVE = TRUE
      AND SNAPSHOT_DATE >= DATEADD(DAY, -29, CURRENT_DATE)
),
agg AS (
    SELECT
        STATE,
        SNAPSHOT_DATE,
        COUNT(DISTINCT CSP_ID) AS cnt
    FROM snap
    GROUP BY STATE, SNAPSHOT_DATE
)
SELECT
    STATE                                                                          AS "State",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE      THEN cnt END)                  AS "D-1",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 1  THEN cnt END)                  AS "D-2",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 2  THEN cnt END)                  AS "D-3",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 3  THEN cnt END)                  AS "D-4",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 4  THEN cnt END)                  AS "D-5",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 5  THEN cnt END)                  AS "D-6",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 6  THEN cnt END)                  AS "D-7",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 7  THEN cnt END)                  AS "D-8",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 8  THEN cnt END)                  AS "D-9",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 9  THEN cnt END)                  AS "D-10",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 10 THEN cnt END)                  AS "D-11",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 11 THEN cnt END)                  AS "D-12",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 12 THEN cnt END)                  AS "D-13",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 13 THEN cnt END)                  AS "D-14",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 14 THEN cnt END)                  AS "D-15",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 15 THEN cnt END)                  AS "D-16",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 16 THEN cnt END)                  AS "D-17",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 17 THEN cnt END)                  AS "D-18",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 18 THEN cnt END)                  AS "D-19",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 19 THEN cnt END)                  AS "D-20",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 20 THEN cnt END)                  AS "D-21",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 21 THEN cnt END)                  AS "D-22",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 22 THEN cnt END)                  AS "D-23",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 23 THEN cnt END)                  AS "D-24",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 24 THEN cnt END)                  AS "D-25",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 25 THEN cnt END)                  AS "D-26",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 26 THEN cnt END)                  AS "D-27",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 27 THEN cnt END)                  AS "D-28",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 28 THEN cnt END)                  AS "D-29",
    MAX(CASE WHEN SNAPSHOT_DATE = CURRENT_DATE - 29 THEN cnt END)                  AS "D-30"
FROM agg
GROUP BY STATE
ORDER BY CASE STATE WHEN 'VERY_GOOD' THEN 1 WHEN 'VG' THEN 1 WHEN 'GOOD' THEN 2 WHEN 'BASE' THEN 3 WHEN 'BASIC' THEN 3 WHEN 'INSUFFICIENT' THEN 4 WHEN 'NOT_APPLICABLE' THEN 5 ELSE 6 END
