WITH csp_universe AS (
  SELECT DISTINCT CSP_ID
  FROM PROD_DB.CSP_GATEWAY_SERVICE_CSP_GATEWAY_SERVICE.CSP_ACCOUNT
  WHERE _FIVETRAN_ACTIVE = TRUE AND STATUS = 'ACTIVE' AND PARTNER_ID IS NOT NULL
),
period_def AS (
    SELECT 'D-1' AS period, 1 AS sk, DATEADD(day,-1,CURRENT_DATE()) AS p_start, DATEADD(day,-1,CURRENT_DATE()) AS p_end
    UNION ALL SELECT 'D-2',2, DATEADD(day,-2,CURRENT_DATE()), DATEADD(day,-2,CURRENT_DATE())
    UNION ALL SELECT 'D-3',3, DATEADD(day,-3,CURRENT_DATE()), DATEADD(day,-3,CURRENT_DATE())
    UNION ALL SELECT 'W-1',4, DATEADD(day,-7,CURRENT_DATE()), DATEADD(day,-1,CURRENT_DATE())
    UNION ALL SELECT 'W-2',5, DATEADD(day,-14,CURRENT_DATE()), DATEADD(day,-8,CURRENT_DATE())
    UNION ALL SELECT 'W-3',6, DATEADD(day,-21,CURRENT_DATE()), DATEADD(day,-15,CURRENT_DATE())
    UNION ALL SELECT 'M-1',7, DATE_TRUNC('month',DATEADD(month,-1,CURRENT_DATE())), LAST_DAY(DATEADD(month,-1,CURRENT_DATE()))
    UNION ALL SELECT 'M-2',8, DATE_TRUNC('month',DATEADD(month,-2,CURRENT_DATE())), LAST_DAY(DATEADD(month,-2,CURRENT_DATE()))
    UNION ALL SELECT 'M-3',9, DATE_TRUNC('month',DATEADD(month,-3,CURRENT_DATE())), LAST_DAY(DATEADD(month,-3,CURRENT_DATE()))
),
srs_base AS (
  SELECT
    s.TICKET_ID,
    CASE
      WHEN s.SECONDARY_SUBTYPE IN ('NEW_PREMISES','WITHIN_PREMISES') THEN 'SHIFTING'
      ELSE COALESCE(s.SECONDARY_SUBTYPE, 'UNKNOWN')
    END AS entry_type,
    DATE(DATEADD(MINUTE, 330, s.CLOSED_TIMESTAMP)) AS closed_dt,
    s.WITHIN_TAT
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS s
  INNER JOIN csp_universe csp ON csp.CSP_ID = s.CSP_ID
  WHERE s._FIVETRAN_ACTIVE = TRUE
    AND s.TICKET_ID IS NOT NULL
    AND s.TICKET_ID NOT LIKE 'prod-test%'
    AND REGEXP_LIKE(s.TICKET_ID, '^[0-9]+$')
    AND s.STATUS = 'CLOSED'
    AND s.CLOSED_TIMESTAMP IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (PARTITION BY s.TICKET_ID ORDER BY s.CREATED_AT DESC, s.VERSION DESC) = 1
),
agg AS (
  SELECT
    CASE WHEN entry_type = '_ALL' THEN '% Resolved Within TAT' ELSE entry_type END AS ENTRY_TYPE,
    CASE WHEN entry_type = '_ALL' THEN 0
         WHEN entry_type = 'NO_INTERNET' THEN 1
         WHEN entry_type = 'RECHARGE_DONE_NO_INTERNET' THEN 2
         WHEN entry_type = 'FREQUENT_DISCONNECTION' THEN 3
         WHEN entry_type = 'SLOW_INTERNET' THEN 4
         WHEN entry_type = 'OPTICAL_POWER_OUT_OF_RANGE' THEN 5
         WHEN entry_type = 'SHIFTING' THEN 6
         END AS rk,
    p.period, p.sk,
    ROUND(100.0 * SUM(CASE WHEN b.WITHIN_TAT = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 1) AS pct
  FROM (
    SELECT entry_type, closed_dt, WITHIN_TAT FROM srs_base
    UNION ALL
    SELECT '_ALL', closed_dt, WITHIN_TAT FROM srs_base
  ) b
  JOIN period_def p ON b.closed_dt BETWEEN p.p_start AND p.p_end
  GROUP BY entry_type, p.period, p.sk
)
SELECT
  ENTRY_TYPE,
  MAX(CASE WHEN period='D-1' THEN pct END) AS "D-1",
  MAX(CASE WHEN period='D-2' THEN pct END) AS "D-2",
  MAX(CASE WHEN period='D-3' THEN pct END) AS "D-3",
  MAX(CASE WHEN period='W-1' THEN pct END) AS "W-1",
  MAX(CASE WHEN period='W-2' THEN pct END) AS "W-2",
  MAX(CASE WHEN period='W-3' THEN pct END) AS "W-3",
  MAX(CASE WHEN period='M-1' THEN pct END) AS "M-1",
  MAX(CASE WHEN period='M-2' THEN pct END) AS "M-2",
  MAX(CASE WHEN period='M-3' THEN pct END) AS "M-3"
FROM agg
WHERE rk IS NOT NULL
GROUP BY ENTRY_TYPE, rk
ORDER BY rk
