WITH params AS (
  SELECT DATE(CONVERT_TIMEZONE('Asia/Kolkata', CURRENT_TIMESTAMP())) AS today
),
migrated AS (
  SELECT DISTINCT ca.CSP_ID
  FROM PROD_DB.CSP_GATEWAY_SERVICE_CSP_GATEWAY_SERVICE.CSP_ACCOUNT ca
  WHERE ca._FIVETRAN_ACTIVE = TRUE AND ca.STATUS = 'ACTIVE'
),
csp_partner AS (
  SELECT DISTINCT ca.PARTNER_ID
  FROM PROD_DB.CSP_GATEWAY_SERVICE_CSP_GATEWAY_SERVICE.CSP_ACCOUNT ca
  WHERE ca._FIVETRAN_ACTIVE = TRUE AND ca.STATUS = 'ACTIVE' AND ca.PARTNER_ID IS NOT NULL
),
kap AS (
  SELECT TICKET_ID,
         DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) AS d
  FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%'
    AND CURRENT_PARTNER_ACCOUNT_ID IN (SELECT PARTNER_ID FROM csp_partner)
    -- Ticket must actually be ON the partner queue, not merely owned by a CSP partner.
    -- ticket-service-java only calls SRS when IS_PARTNERASSIGNED (TicketCreationUtils.java:382),
    -- so Wiom Net / Tech queue tickets can never produce a complaint and must not sit in the denominator.
    AND IS_PARTNERASSIGNED = 1
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) >= DATEADD('day', -130, CURRENT_DATE())
),
comp_ids AS (
  SELECT DISTINCT TICKET_ID
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE = TRUE
    AND TICKET_ID NOT LIKE 'prod-test%'
    AND SECONDARY_SUBTYPE IN ('OPTICAL_POWER_OUT_OF_RANGE','RECHARGE_DONE_NO_INTERNET','FREQUENT_DISCONNECTION','SLOW_INTERNET','NO_INTERNET')
    AND CSP_ID IN (SELECT CSP_ID FROM migrated)
),
base AS (
  SELECT k.d,
         k.TICKET_ID AS entity_id,
         CASE WHEN c.TICKET_ID IS NOT NULL THEN 1 ELSE 0 END AS flag
  FROM kap k
  LEFT JOIN comp_ids c ON k.TICKET_ID = c.TICKET_ID
)
SELECT 'Service Ticket Cross-Table Match Rate' AS kpi,
  1.0*COUNT(DISTINCT CASE WHEN d = p.today-1 AND flag=1 THEN entity_id END)/NULLIF(COUNT(DISTINCT CASE WHEN d = p.today-1 THEN entity_id END),0)*100 AS "D-1",
  1.0*COUNT(DISTINCT CASE WHEN d = p.today-2 AND flag=1 THEN entity_id END)/NULLIF(COUNT(DISTINCT CASE WHEN d = p.today-2 THEN entity_id END),0)*100 AS "D-2",
  1.0*COUNT(DISTINCT CASE WHEN d = p.today-3 AND flag=1 THEN entity_id END)/NULLIF(COUNT(DISTINCT CASE WHEN d = p.today-3 THEN entity_id END),0)*100 AS "D-3",
  1.0*COUNT(DISTINCT CASE WHEN d BETWEEN DATEADD('day',-7, DATE_TRUNC('week',p.today)) AND DATEADD('day',-1, DATE_TRUNC('week',p.today)) AND flag=1 THEN entity_id END)/NULLIF(COUNT(DISTINCT CASE WHEN d BETWEEN DATEADD('day',-7, DATE_TRUNC('week',p.today)) AND DATEADD('day',-1, DATE_TRUNC('week',p.today)) THEN entity_id END),0)*100 AS "W-1",
  1.0*COUNT(DISTINCT CASE WHEN d BETWEEN DATEADD('day',-14,DATE_TRUNC('week',p.today)) AND DATEADD('day',-8, DATE_TRUNC('week',p.today)) AND flag=1 THEN entity_id END)/NULLIF(COUNT(DISTINCT CASE WHEN d BETWEEN DATEADD('day',-14,DATE_TRUNC('week',p.today)) AND DATEADD('day',-8, DATE_TRUNC('week',p.today)) THEN entity_id END),0)*100 AS "W-2",
  1.0*COUNT(DISTINCT CASE WHEN d BETWEEN DATEADD('day',-21,DATE_TRUNC('week',p.today)) AND DATEADD('day',-15,DATE_TRUNC('week',p.today)) AND flag=1 THEN entity_id END)/NULLIF(COUNT(DISTINCT CASE WHEN d BETWEEN DATEADD('day',-21,DATE_TRUNC('week',p.today)) AND DATEADD('day',-15,DATE_TRUNC('week',p.today)) THEN entity_id END),0)*100 AS "W-3",
  1.0*COUNT(DISTINCT CASE WHEN DATE_TRUNC('month',d) = DATEADD('month',-1,DATE_TRUNC('month',p.today)) AND flag=1 THEN entity_id END)/NULLIF(COUNT(DISTINCT CASE WHEN DATE_TRUNC('month',d) = DATEADD('month',-1,DATE_TRUNC('month',p.today)) THEN entity_id END),0)*100 AS "M-1",
  1.0*COUNT(DISTINCT CASE WHEN DATE_TRUNC('month',d) = DATEADD('month',-2,DATE_TRUNC('month',p.today)) AND flag=1 THEN entity_id END)/NULLIF(COUNT(DISTINCT CASE WHEN DATE_TRUNC('month',d) = DATEADD('month',-2,DATE_TRUNC('month',p.today)) THEN entity_id END),0)*100 AS "M-2",
  1.0*COUNT(DISTINCT CASE WHEN DATE_TRUNC('month',d) = DATEADD('month',-3,DATE_TRUNC('month',p.today)) AND flag=1 THEN entity_id END)/NULLIF(COUNT(DISTINCT CASE WHEN DATE_TRUNC('month',d) = DATEADD('month',-3,DATE_TRUNC('month',p.today)) THEN entity_id END),0)*100 AS "M-3"
FROM base CROSS JOIN params p
